// 社内wikiサンプルデータ
export const wikiArticles: WikiArticle[] = [
    {
        "id": 1,
        "title": "新入社員オンボーディングガイド",
        "category": "人事・総務",
        "summary": "新入社員が入社後にスムーズに業務を開始できるよう、必要な手続きや研修について説明します。",
        "content": "## 入社初日の流れ\n1. 受付での手続き\n2. IDカード・PC受け取り\n3. オリエンテーション参加\n\n## 必要書類\n- 雇用契約書\n- 身元保証書\n- マイナンバー関連書類",
        "author": "田中太郎",
        "department": "人事部",
        "created_date": "2024-04-01",
        "updated_date": "2024-08-15",
        "tags": ["新入社員", "オンボーディング", "人事"],
        "status": "published",
        "views": 245
    },
    {
        "id": 2,
        "title": "Slackの使い方ガイド",
        "category": "ITツール",
        "summary": "社内コミュニケーションツールSlackの基本的な使い方と運用ルールについて解説します。",
        "content": "## 基本機能\n- チャンネル作成・参加方法\n- ダイレクトメッセージ\n- ファイル共有\n\n## 運用ルール\n- 業務時間外の通知設定\n- チャンネル命名規則\n- スレッド機能の活用",
        "author": "佐藤花子",
        "department": "IT部",
        "created_date": "2024-03-15",
        "updated_date": "2024-07-20",
        "tags": ["Slack", "コミュニケーション", "ツール"],
        "status": "published",
        "views": 532
    },
    {
        "id": 3,
        "title": "経費精算システムの使い方",
        "category": "経理・財務",
        "summary": "経費精算システムでの申請から承認までのフローを詳しく説明します。",
        "content": "## 申請手順\n1. システムログイン\n2. 経費項目入力\n3. レシート画像添付\n4. 上長承認申請\n\n## 注意事項\n- 申請期限は月末から7営業日以内\n- 領収書は必ず原本を保管",
        "author": "鈴木一郎",
        "department": "経理部",
        "created_date": "2024-02-10",
        "updated_date": "2024-06-30",
        "tags": ["経費精算", "システム", "申請"],
        "status": "published",
        "views": 389
    },
    {
        "id": 4,
        "title": "リモートワークガイドライン",
        "category": "働き方",
        "summary": "在宅勤務・リモートワークを行う際のルールと推奨環境について説明します。",
        "content": "## 勤務時間\n- コアタイム：10:00-15:00\n- フレックス対応可能\n\n## 必要環境\n- 安定したインターネット接続\n- セキュリティソフト導入\n- 静かな作業環境",
        "author": "山田美咲",
        "department": "人事部",
        "created_date": "2024-01-20",
        "updated_date": "2024-05-10",
        "tags": ["リモートワーク", "在宅勤務", "働き方"],
        "status": "published",
        "views": 678
    },
    {
        "id": 5,
        "title": "Git・GitHubワークフロー",
        "category": "開発",
        "summary": "開発チームでのGitとGitHubを使った効率的な開発フローについて解説します。",
        "content": "## ブランチ戦略\n- main: プロダクションブランチ\n- develop: 開発統合ブランチ\n- feature: 機能開発ブランチ\n\n## プルリクエストルール\n- コードレビュー必須\n- テスト通過確認\n- 適切なコミットメッセージ",
        "author": "高橋健太",
        "department": "開発部",
        "created_date": "2024-03-01",
        "updated_date": "2024-08-01",
        "tags": ["Git", "GitHub", "開発フロー"],
        "status": "published",
        "views": 456
    },
    {
        "id": 6,
        "title": "セキュリティポリシー",
        "category": "セキュリティ",
        "summary": "情報セキュリティに関する社内ポリシーと遵守事項について説明します。",
        "content": "## パスワード管理\n- 定期的な変更（90日毎）\n- 複雑なパスワード設定\n- パスワード管理ツール推奨\n\n## データ取り扱い\n- 機密データの持ち出し禁止\n- USBメモリ使用制限\n- メール送信時の暗号化",
        "author": "渡辺修司",
        "department": "IT部",
        "created_date": "2024-01-15",
        "updated_date": "2024-07-15",
        "tags": ["セキュリティ", "ポリシー", "情報管理"],
        "status": "published",
        "views": 723
    },
    {
        "id": 7,
        "title": "会議室予約システム",
        "category": "オフィス環境",
        "summary": "会議室の予約方法と利用ルールについて説明します。",
        "content": "## 予約方法\n1. Outlookカレンダーから予約\n2. 会議室リソース選択\n3. 必要機材も同時予約\n\n## 利用ルール\n- 5分以上遅刻時は自動キャンセル\n- 終了5分前に片付け開始\n- 機材トラブル時はIT部へ連絡",
        "author": "伊藤麻衣",
        "department": "総務部",
        "created_date": "2024-02-28",
        "updated_date": "2024-06-15",
        "tags": ["会議室", "予約システム", "オフィス"],
        "status": "published",
        "views": 334
    },
    {
        "id": 8,
        "title": "プロジェクト管理ツール (Jira) 使い方",
        "category": "プロジェクト管理",
        "summary": "JiraによるプロジェクトとタスクのRSP方法について解説します。",
        "content": "## チケット作成\n- 適切なプロジェクト選択\n- 詳細な説明記入\n- 優先度・期日設定\n\n## ワークフロー\n1. ToDo → In Progress → Review → Done\n2. 各ステータスでの作業内容\n3. レポート機能活用法",
        "author": "小林大輔",
        "department": "開発部",
        "created_date": "2024-03-10",
        "updated_date": "2024-08-05",
        "tags": ["Jira", "プロジェクト管理", "タスク"],
        "status": "published",
        "views": 425
    },
    {
        "id": 9,
        "title": "年次有給休暇取得ガイド",
        "category": "人事・総務",
        "summary": "有給休暇の取得方法と注意事項について説明します。",
        "content": "## 申請方法\n1. 人事システムから申請\n2. 上長承認\n3. チームメンバーへの業務引継ぎ\n\n## 取得ルール\n- 事前申請が原則（緊急時除く）\n- 繁忙期は調整が必要\n- 年間取得目標：最低5日以上",
        "author": "青木智子",
        "department": "人事部",
        "created_date": "2024-04-05",
        "updated_date": "2024-07-01",
        "tags": ["有給休暇", "申請", "人事制度"],
        "status": "published",
        "views": 512
    },
    {
        "id": 10,
        "title": "クラウドストレージ (Google Drive) 運用ルール",
        "category": "ITツール",
        "summary": "Google Driveを使った効率的なファイル管理と共有方法について解説します。",
        "content": "## フォルダ構成\n- 部門別フォルダ\n- プロジェクト別サブフォルダ\n- 個人作業フォルダ\n\n## 共有設定\n- 社内限定共有推奨\n- 編集権限の適切な設定\n- リンク共有時の注意事項",
        "author": "松本裕子",
        "department": "IT部",
        "created_date": "2024-02-15",
        "updated_date": "2024-06-20",
        "tags": ["Google Drive", "ファイル管理", "クラウド"],
        "status": "published",
        "views": 398
    },
    {
        "id": 11,
        "title": "営業活動報告書の書き方",
        "category": "営業・販売",
        "summary": "効果的な営業活動報告書の作成方法とテンプレート使用方法について説明します。",
        "content": "## 報告書の構成\n1. 顧客情報\n2. 商談内容\n3. 次回アクション\n4. 課題・懸念事項\n\n## 記入のポイント\n- 具体的な数値記載\n- 客観的な事実記述\n- 次回提案内容の明確化",
        "author": "中村優介",
        "department": "営業部",
        "created_date": "2024-01-25",
        "updated_date": "2024-05-30",
        "tags": ["営業", "報告書", "商談"],
        "status": "published",
        "views": 289
    },
    {
        "id": 12,
        "title": "災害時行動マニュアル",
        "category": "安全管理",
        "summary": "地震・火災等の災害発生時の避難手順と連絡体制について説明します。",
        "content": "## 避難手順\n1. 身の安全確保\n2. 火元確認・消火\n3. 避難経路確認\n4. 指定避難場所へ移動\n\n## 連絡体制\n- 安否確認システム利用\n- 緊急連絡先一覧\n- 災害対策本部設置",
        "author": "森田実",
        "department": "総務部",
        "created_date": "2024-01-10",
        "updated_date": "2024-04-10",
        "tags": ["災害対策", "避難", "安全管理"],
        "status": "published",
        "views": 156
    },
    {
        "id": 13,
        "title": "顧客情報管理システム (CRM) 活用法",
        "category": "営業・販売",
        "summary": "CRMシステムを活用した効率的な顧客管理と営業活動について解説します。",
        "content": "## 顧客データ入力\n- 基本情報の正確な入力\n- 商談履歴の記録\n- フォローアップ予定設定\n\n## レポート活用\n- 売上予測レポート\n- 顧客分析ダッシュボード\n- 活動実績集計",
        "author": "岡田あゆみ",
        "department": "営業部",
        "created_date": "2024-02-20",
        "updated_date": "2024-06-25",
        "tags": ["CRM", "顧客管理", "営業支援"],
        "status": "published",
        "views": 367
    },
    {
        "id": 14,
        "title": "テスト環境構築ガイド",
        "category": "開発",
        "summary": "開発・ステージング・本番環境の構築手順と注意事項について説明します。",
        "content": "## 環境構成\n- Development環境\n- Staging環境\n- Production環境\n\n## 構築手順\n1. Dockerコンテナ作成\n2. 環境変数設定\n3. データベース初期化\n4. 動作確認テスト",
        "author": "石川達也",
        "department": "開発部",
        "created_date": "2024-03-20",
        "updated_date": "2024-07-10",
        "tags": ["テスト環境", "インフラ", "Docker"],
        "status": "published",
        "views": 234
    },
    {
        "id": 15,
        "title": "チームビルディング活動ガイド",
        "category": "人材育成",
        "summary": "効果的なチームビルディング活動の企画・実施方法について説明します。",
        "content": "## 活動例\n- ワークショップ形式\n- アウトドア活動\n- オンライン交流会\n\n## 企画のポイント\n- 参加者全員が楽しめる内容\n- コミュニケーション促進\n- 予算・時間の適切な管理",
        "author": "坂本真理",
        "department": "人事部",
        "created_date": "2024-04-15",
        "updated_date": "2024-08-20",
        "tags": ["チームビルディング", "研修", "コミュニケーション"],
        "status": "published",
        "views": 445
    },
    {
        "id": 16,
        "title": "予算管理システム操作マニュアル",
        "category": "経理・財務",
        "summary": "予算策定から実績管理まで、予算管理システムの操作方法を解説します。",
        "content": "## 予算策定\n1. 年次予算入力\n2. 四半期予算配分\n3. 部門承認フロー\n\n## 実績管理\n- 月次実績取り込み\n- 予算差異分析\n- レポート出力機能",
        "author": "長谷川光",
        "department": "経理部",
        "created_date": "2024-01-30",
        "updated_date": "2024-05-15",
        "tags": ["予算管理", "財務", "システム"],
        "status": "published",
        "views": 178
    },
    {
        "id": 17,
        "title": "在庫管理システム運用手順",
        "category": "業務システム",
        "summary": "在庫の入庫・出庫管理から棚卸しまでのシステム操作について説明します。",
        "content": "## 入出庫管理\n- 入庫伝票入力\n- 出庫処理実行\n- 在庫残高確認\n\n## 棚卸し作業\n1. 実地棚卸し実施\n2. システム在庫との照合\n3. 差異調整処理",
        "author": "西村和也",
        "department": "物流部",
        "created_date": "2024-02-05",
        "updated_date": "2024-06-10",
        "tags": ["在庫管理", "物流", "システム"],
        "status": "published",
        "views": 267
    },
    {
        "id": 18,
        "title": "新製品開発プロセス",
        "category": "商品企画",
        "summary": "商品企画から市場投入までの新製品開発の標準的なプロセスについて説明します。",
        "content": "## 開発フェーズ\n1. 市場調査・企画\n2. 設計・試作\n3. テスト・検証\n4. 量産・販売開始\n\n## 各段階の成果物\n- 企画書・仕様書\n- プロトタイプ\n- テスト結果報告\n- 販売計画書",
        "author": "加藤雅人",
        "department": "商品企画部",
        "created_date": "2024-03-25",
        "updated_date": "2024-07-25",
        "tags": ["新製品開発", "商品企画", "プロセス"],
        "status": "published",
        "views": 356
    },
    {
        "id": 19,
        "title": "コンプライアンス研修資料",
        "category": "法務・コンプライアンス",
        "summary": "企業倫理とコンプライアンス遵守に関する基本的な考え方と実践方法について説明します。",
        "content": "## 基本原則\n- 法令遵守の徹底\n- 公正な取引の実践\n- 情報の適切な管理\n\n## 具体的な行動指針\n- 利益相反の回避\n- ハラスメント防止\n- 内部通報制度の活用",
        "author": "藤田康弘",
        "department": "法務部",
        "created_date": "2024-01-05",
        "updated_date": "2024-04-20",
        "tags": ["コンプライアンス", "企業倫理", "法令遵守"],
        "status": "published",
        "views": 623
    },
    {
        "id": 20,
        "title": "社内イベント企画・運営マニュアル",
        "category": "総務・庶務",
        "summary": "歓送迎会、忘年会などの社内イベントの企画から運営までの手順を説明します。",
        "content": "## 企画準備\n1. 予算設定\n2. 会場選定\n3. 参加者募集\n4. プログラム作成\n\n## 当日運営\n- 受付・誘導\n- 進行管理\n- 写真撮影\n- 片付け・清算",
        "author": "三浦奈々子",
        "department": "総務部",
        "created_date": "2024-04-10",
        "updated_date": "2024-08-10",
        "tags": ["社内イベント", "企画", "運営"],
        "status": "published",
        "views": 412
    }
]