// 社内wikiサンプルデータ
export const wikiArticles: WikiArticle[] = [
    {
        "id": "1",
        "title": "新入社員オンボーディングガイド",
        "category": "人事・総務",
        "summary": "新入社員が入社後にスムーズに業務を開始できるよう、必要な手続きや研修について説明します。",
        "content": "## 入社初日の流れ\n1. 受付での手続き\n2. IDカード・PC受け取り\n3. オリエンテーション参加\n\n## 必要書類\n- 雇用契約書\n- 身元保証書\n- マイナンバー関連書類",
        "author": "田中太郎",
        "department": "人事部",
        "createdAt": "2024-04-01",
        "updatedAt": "2024-08-15",
        "tags": ["新入社員", "オンボーディング", "人事"],
        "status": "published",
        "views": 245
    },
    {
        "id": "2",
        "title": "Slackの使い方ガイド",
        "category": "ITツール",
        "summary": "社内コミュニケーションツールSlackの基本的な使い方と運用ルールについて解説します。",
        "content": "## 基本機能\n- チャンネル作成・参加方法\n- ダイレクトメッセージ\n- ファイル共有\n\n## 運用ルール\n- 業務時間外の通知設定\n- チャンネル命名規則\n- スレッド機能の活用",
        "author": "佐藤花子",
        "department": "IT部",
        "createdAt": "2024-03-15",
        "updatedAt": "2024-07-20",
        "tags": ["Slack", "コミュニケーション", "ツール"],
        "status": "published",
        "views": 532
    },
    {
        "id": "3",
        "title": "経費精算システムの使い方",
        "category": "経理・財務",
        "summary": "経費精算システムでの申請から承認までのフローを詳しく説明します。",
        "content": "## 申請手順\n1. システムログイン\n2. 経費項目入力\n3. レシート画像添付\n4. 上長承認申請\n\n## 注意事項\n- 申請期限は月末から7営業日以内\n- 領収書は必ず原本を保管",
        "author": "鈴木一郎",
        "department": "経理部",
        "createdAt": "2024-02-10",
        "updatedAt": "2024-06-30",
        "tags": ["経費精算", "システム", "申請"],
        "status": "published",
        "views": 389
    },
    {
        "id": "4",
        "title": "リモートワークガイドライン",
        "category": "働き方",
        "summary": "在宅勤務・リモートワークを行う際のルールと推奨環境について説明します。",
        "content": "## 勤務時間\n- コアタイム：10:00-15:00\n- フレックス対応可能\n\n## 必要環境\n- 安定したインターネット接続\n- セキュリティソフト導入\n- 静かな作業環境",
        "author": "山田美咲",
        "department": "人事部",
        "createdAt": "2024-01-20",
        "updatedAt": "2024-05-10",
        "tags": ["リモートワーク", "在宅勤務", "働き方"],
        "status": "published",
        "views": 678
    },
    {
        "id": "5",
        "title": "Git・GitHubワークフロー",
        "category": "開発",
        "summary": "開発チームでのGitとGitHubを使った効率的な開発フローについて解説します。",
        "content": "## ブランチ戦略\n- main: プロダクションブランチ\n- develop: 開発統合ブランチ\n- feature: 機能開発ブランチ\n\n## プルリクエストルール\n- コードレビュー必須\n- テスト通過確認\n- 適切なコミットメッセージ",
        "author": "高橋健太",
        "department": "開発部",
        "createdAt": "2024-03-01",
        "updatedAt": "2024-08-01",
        "tags": ["Git", "GitHub", "開発フロー"],
        "status": "published",
        "views": 456
    },
    {
        "id": "6",
        "title": "セキュリティポリシー",
        "category": "セキュリティ",
        "summary": "情報セキュリティに関する社内ポリシーと遵守事項について説明します。",
        "content": "## パスワード管理\n- 定期的な変更（90日毎）\n- 複雑なパスワード設定\n- パスワード管理ツール推奨\n\n## データ取り扱い\n- 機密データの持ち出し禁止\n- USBメモリ使用制限\n- メール送信時の暗号化",
        "author": "渡辺修司",
        "department": "IT部",
        "createdAt": "2024-01-15",
        "updatedAt": "2024-07-15",
        "tags": ["セキュリティ", "ポリシー", "情報管理"],
        "status": "published",
        "views": 723
    },
    {
        "id": "7",
        "title": "会議室予約システム",
        "category": "オフィス環境",
        "summary": "会議室の予約方法と利用ルールについて説明します。",
        "content": "## 予約方法\n1. Outlookカレンダーから予約\n2. 会議室リソース選択\n3. 必要機材も同時予約\n\n## 利用ルール\n- 5分以上遅刻時は自動キャンセル\n- 終了5分前に片付け開始\n- 機材トラブル時はIT部へ連絡",
        "author": "伊藤麻衣",
        "department": "総務部",
        "createdAt": "2024-02-28",
        "updatedAt": "2024-06-15",
        "tags": ["会議室", "予約システム", "オフィス"],
        "status": "published",
        "views": 334
    },
    {
        "id": "8",
        "title": "プロジェクト管理ツール (Jira) 使い方",
        "category": "プロジェクト管理",
        "summary": "JiraによるプロジェクトとタスクのRSP方法について解説します。",
        "content": "## チケット作成\n- 適切なプロジェクト選択\n- 詳細な説明記入\n- 優先度・期日設定\n\n## ワークフロー\n1. ToDo → In Progress → Review → Done\n2. 各ステータスでの作業内容\n3. レポート機能活用法",
        "author": "小林大輔",
        "department": "開発部",
        "createdAt": "2024-03-10",
        "updatedAt": "2024-08-05",
        "tags": ["Jira", "プロジェクト管理", "タスク"],
        "status": "published",
        "views": 425
    }
]