export const useConstants = () => {
    const chartTypes = [
        {
            id: '1',
            value: 'bar',
            name: '棒グラフ',
            icon: 'mdi-chart-bar',
            settings: [
                { key: 'title', name: 'タイトル', type: 'text' },
                { key: 'label', name: 'ラベル', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'value', name: '値', type: 'select', accepts: ['number', 'calculate'] },
                { key: 'orderKey', name: '並び順キー', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'orderDivision', name: '並び替え方向', type: 'select', items: [{ value: 'ascending', title: '昇順' }, { value: 'descending', title: '降順' }] },
            ],
            x: 0,
            y: 0,
            w: 26,
            h: 30,
            i: 0,
            metaField: {},
        },
        {
            id: '2',
            value: 'bubble',
            name: 'バブルチャート',
            icon: 'mdi-chart-bubble',
            settings: [
                { key: 'title', name: 'タイトル', type: 'text' },
                { key: 'xValue', name: 'x軸', type: 'select', accepts: ['number', 'calculate'] },
                { key: 'yValue', name: 'y軸', type: 'select', accepts: ['number', 'calculate'] },
                { key: 'rValue', name: '大きさ', type: 'select', accepts: ['number', 'calculate'] },
                { key: 'orderKey', name: '並び順キー', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'orderDivision', name: '並び替え方向', type: 'select', items: [{ value: 'ascending', title: '昇順' }, { value: 'descending', title: '降順' }] },
            ],
            x: 0,
            y: 0,
            w: 26,
            h: 30,
            i: 0,
            metaField: {},
        },
        {
            id: '3',
            value: 'doughnut',
            name: 'ドーナツグラフ',
            icon: 'mdi-chart-donut',
            settings: [
                { key: 'title', name: 'タイトル', type: 'text' },
                { key: 'label', name: 'ラベル', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'value', name: '値', type: 'select', accepts: ['number', 'calculate'] },
                { key: 'orderKey', name: '並び順キー', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'orderDivision', name: '並び替え方向', type: 'select', items: [{ value: 'ascending', title: '昇順' }, { value: 'descending', title: '降順' }] },
            ],
            x: 0,
            y: 0,
            w: 26,
            h: 30,
            i: 0,
            metaField: {},
        },
        {
            id: '4',
            value: 'line',
            name: '折れ線グラフ',
            icon: 'mdi-chart-line',
            settings: [
                { key: 'title', name: 'タイトル', type: 'text' },
                { key: 'label', name: 'ラベル', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'value', name: '値', type: 'select', accepts: ['number', 'calculate'] },
                { key: 'orderKey', name: '並び順キー', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'orderDivision', name: '並び替え方向', type: 'select', items: [{ value: 'ascending', title: '昇順' }, { value: 'descending', title: '降順' }] },
            ],
            x: 0,
            y: 0,
            w: 26,
            h: 30,
            i: 0,
            metaField: {},
        },
        {
            id: '5',
            value: 'pie',
            name: '円グラフ',
            icon: 'mdi-chart-pie-outline',
            settings: [
                { key: 'title', name: 'タイトル', type: 'text' },
                { key: 'label', name: 'ラベル', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'value', name: '値', type: 'select', accepts: ['number', 'calculate'] },
                { key: 'orderKey', name: '並び順キー', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'orderDivision', name: '並び替え方向', type: 'select', items: [{ value: 'ascending', title: '昇順' }, { value: 'descending', title: '降順' }] },
            ],
            x: 0,
            y: 0,
            w: 26,
            h: 30,
            i: 0,
            metaField: {},
        },
        {
            id: '6',
            value: 'polarArea',
            name: '鶏頭図',
            icon: 'mdi-chart-arc',
            settings: [
                { key: 'title', name: 'タイトル', type: 'text' },
                { key: 'label', name: 'ラベル', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'value', name: '値', type: 'select', accepts: ['number', 'calculate'] },
                { key: 'orderKey', name: '並び順キー', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'orderDivision', name: '並び替え方向', type: 'select', items: [{ value: 'ascending', title: '昇順' }, { value: 'descending', title: '降順' }] },
            ],
            x: 0,
            y: 0,
            w: 26,
            h: 30,
            i: 0,
            metaField: {},
        },
        {
            id: '7',
            value: 'radar',
            name: 'レーダーグラフ',
            icon: 'mdi-radar',
            settings: [
                { key: 'title', name: 'タイトル', type: 'text' },
                { key: 'label', name: 'ラベル', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'value', name: '値', type: 'select', accepts: ['number', 'calculate'] },
                { key: 'fill', name: '塗りつぶし', type: 'radio', items: [{ value: true, title: 'true' }, { value: false, title: 'false' }] },
                { key: 'orderKey', name: '並び順キー', type: 'select', accepts: ['date', 'datetime', 'number', 'object', 'text', 'time', 'calculate', 'text-join'] },
                { key: 'orderDivision', name: '並び替え方向', type: 'select', items: [{ value: 'ascending', title: '昇順' }, { value: 'descending', title: '降順' }] },
            ],
            x: 0,
            y: 0,
            w: 26,
            h: 30,
            i: 0,
            metaField: {},
        },
        {
            id: '8',
            value: 'scatter',
            name: '散布図',
            icon: 'mdi-chart-scatter-plot',
            settings: [
                { key: 'title', name: 'タイトル', type: 'text' },
                { key: 'xValue', name: 'x軸', type: 'select', accepts: ['number', 'calculate'] },
                { key: 'yValue', name: 'y軸', type: 'select', accepts: ['number', 'calculate'] },
            ],
            x: 0,
            y: 0,
            w: 26,
            h: 30,
            i: 0,
            metaField: {},
        },
    ] as ChartType[]

    const dataSources = [
        { id: 1, title: 'Firestore', value: 'firestore', metaField: {} },
        // { id: 2, title: 'CloudStorage', value: 'cloudStorage', metaField: {} },
        // { id: 3, title: 'スプレッドシート', value: 'spreadSheet', metaField: {} },
        // { id: 4, title: 'Api', value: 'api', metaField: {} },
    ] as DataSource[]

    const pageContents = [
        { componentId: 1, name: 'ラベル', icon: 'mdi-tag', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: 'ラベル', en: '' }, type: 'text', component: 'label', searchable: false, metaField: {}, hasData: false, action: 'none' } as AppField },
        { componentId: 2, name: '文字列(1行)', icon: 'mdi-alphabetical-variant', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: '文字列(1行)', en: '' }, type: 'text', component: 'text', searchable: false, metaField: {}, hasData: true, action: 'input' } as AppField },
        { componentId: 3, name: '文字列(複数行)', icon: 'mdi-text-box-outline', x: 0, y: 0, w: 51, h: 12, i: 0, field: { label: { ja: '文字列(複数行)', en: '' }, type: 'memo', component: 'textarea', searchable: false, metaField: {}, hasData: true, action: 'input' } as AppField },
        { componentId: 4, name: '数値', icon: 'mdi-numeric', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: '数値', en: '' }, type: 'number', component: 'number', searchable: false, metaField: {}, hasData: true, action: 'input' } as AppField },
        { componentId: 5, name: '計算', icon: 'mdi-calculator-variant', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: '計算', en: '' }, type: 'calculate', component: 'calculation', searchable: false, metaField: {}, hasData: false, action: 'calculate' } as AppField },
        { componentId: 6, name: 'ラジオボタン', icon: 'mdi-radiobox-marked', x: 0, y: 0, w: 51, h: 9, i: 0, field: { label: { ja: 'ラジオボタン', en: '' }, type: 'object', component: 'radio', searchable: false, metaField: { items: [{ index: 0, title: '', value: undefined }], inline: true }, hasData: true, action: 'input' } as AppField },
        { componentId: 7, name: 'チェックボックス', icon: 'mdi-checkbox-marked-outline', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: 'チェックボックス', en: '' }, type: 'boolen', component: 'checkbox', searchable: false, metaField: {}, hasData: true, action: 'input' } as AppField },
        { componentId: 8, name: '複数選択', icon: 'mdi-form-select', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: '複数選択', en: '' }, type: 'object', component: 'multi-selector', searchable: false, metaField: { items: [{ index: 0, title: '', value: undefined }] }, hasData: true, action: 'input' } as AppField },
        { componentId: 9, name: 'ドロップダウン', icon: 'mdi-form-dropdown', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: 'ドロップダウン', en: '' }, type: 'object', component: 'dropdown', searchable: false, metaField: { items: [{ index: 0, title: '', value: undefined }] }, hasData: true, action: 'input' } as AppField },
        { componentId: 10, name: '日付', icon: 'mdi-calendar-month-outline', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: '日付', en: '' }, type: 'date', component: 'date', searchable: false, metaField: {}, hasData: true, action: 'input' } as AppField },
        { componentId: 11, name: '時間', icon: 'mdi-clock-time-two-outline', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: '時間', en: '' }, type: 'time', component: 'time', searchable: false, metaField: {}, hasData: true, action: 'input' } as AppField },
        { componentId: 12, name: '日時', icon: 'mdi-calendar-clock', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: '日時', en: '' }, type: 'datetime', component: 'datetime', searchable: false, metaField: {}, hasData: true, action: 'input' } as AppField },
        { componentId: 13, name: '添付ファイル', icon: 'mdi-paperclip', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: '添付ファイル', en: '' }, type: 'file', component: 'file', searchable: false, metaField: {}, hasData: true, action: 'input' } as AppField },
        { componentId: 14, name: 'リンク', icon: 'mdi-link', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: 'リンク', en: '' }, type: 'text', component: 'link', searchable: false, metaField: {}, hasData: false, action: 'click' } as AppField },
        { componentId: 15, name: 'ユーザー選択', icon: 'mdi-account-check-outline', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: 'ユーザー選択', en: '' }, type: 'object', component: 'user-selector', searchable: false, metaField: { items: [{ index: 0, title: '', value: undefined }] }, hasData: true, action: 'input' } as AppField },
        // { componentId: 16, name: 'スペース', icon: 'mdi-keyboard-space', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: 'スペース', en: '' }, type: 'none', component: 'space', searchable: false, metaField: {}, hasData: false, action: 'none' } as AppField },
        { componentId: 17, name: '罫線', icon: 'mdi-minus', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: '罫線', en: '' }, type: 'none', component: 'divider', searchable: false, metaField: {}, hasData: false, action: 'none' } as AppField },
        { componentId: 18, name: 'テーブル', icon: 'mdi-table-large', x: 0, y: 0, w: 51, h: 15, i: 0, field: { label: { ja: 'テーブル', en: '' }, type: 'object', component: 'table', searchable: false, metaField: { rowHeaders: [{ index: 0, title: '' }], colHeaders: [{ index: 0, title: '' }] }, hasData: true, action: 'input' } as AppField },
        // { componentId: 19, name: 'ボタン', icon: 'mdi-button-cursor', x: 0, y: 0, w: 51, h: 5, i: 0, field: { label: { ja: 'ボタン', en: '' }, type: 'none', component: 'button', searchable: false, metaField: {}, hasData: false, action: 'click' } as AppField },
        // { componentId: 20, name: 'グラフ', icon: 'mdi-chart-line', x: 0, y: 0, w: 51, h: 15, i: 0, field: { label: { ja: 'グラフ', en: '' }, type: 'view', component: 'chart', searchable: false, metaField: {}, hasData: false, action: 'none' } as AppField },
        { componentId: 21, name: 'ピクトピア', icon: 'mdi-image-outline', x: 0, y: 0, w: 51, h: 15, i: 0, field: { label: { ja: '画像', en: '' }, type: 'image', component: 'pictpia-input', searchable: false, metaField: {}, hasData: true, action: 'input' } as AppField },
        { componentId: 22, name: '結合文字列', icon: 'mdi-vector-union', x: 0, y: 0, w: 51, h: 6, i: 0, field: { label: { ja: '結合文字列', en: '' }, type: 'text-join', component: 'text-join', searchable: false, metaField: {}, hasData: false, action: 'calculate' } as AppField },
    ] as AppContent[]

    const viewTypes = [
        { id: 1, title: 'リスト', value: 'table', metaField: {} },
        { id: 2, title: '画像カード', value: 'pictpia', metaField: {} },
    ] as ViewType[]

    const roles = [
        { id: 1, title: '管理者', value: 'admin', metaField: {} },
        { id: 2, title: '一般', value: 'user', metaField: {} },
    ] as Role[]

    const invitationStatus = {
        inviting: {
            name: '承認待ち',
            color: 'warning',
        },
        accepted: {
            name: '承認済',
            color: 'success',
        },
        declined: {
            name: '辞退',
            color: 'error',
        },
        expirationed: {
            name: '期限切れ',
            color: 'error',
        }
    }

    return {
        chartTypes,
        dataSources,
        pageContents,
        viewTypes,
        roles,
        invitationStatus,
    }
}